sudo: false
language: python
python:
  - "3.5"
  # More versions later.

install:
  - pip install git+git://github.com/JukkaL/mypy

script:
  - mypy stdlib/3/
  - mypy stdlib/2and3/
  - rm -rf 3_3; cp -R stdlib/3.3 3_3; mypy 3_3/
  - rm -rf 3_4; cp -R stdlib/3.4 3_4; mypy 3_4/
  - mypy --py2 stdlib/2and3/
  - rm -rf 2_7; cp -R -L stdlib/2.7 2_7; rm 2_7/__builtin__.pyi ; mypy --py2 2_7/
  - for X in third_party/{3*,2and3}; do echo $X; rm -rf tmp; cp -R -L $X/ tmp; mypy tmp/; done
  - for X in third_party/{2*,2and3}; do echo $X; rm -rf tmp; cp -R -L $X/ tmp; mypy --py2 tmp/; done
